Chord::NumericalChord.create!([
  {chord_base_id: 3, modification_ids: [], base: 1, quality: ""},
  {chord_base_id: 4, modification_ids: [], base: 1, quality: "m"},
  {chord_base_id: 4, modification_ids: [], base: 11, quality: "m"},
  {chord_base_id: 3, modification_ids: [], base: 2, quality: ""},
  {chord_base_id: 4, modification_ids: [], base: 4, quality: "m"},
  {chord_base_id: 3, modification_ids: [], base: 6, quality: ""},
  {chord_base_id: 3, modification_ids: [], base: 9, quality: ""},
  {chord_base_id: 3, modification_ids: [], base: 7, quality: ""},
  {chord_base_id: 3, modification_ids: [], base: 4, quality: ""},
  {chord_base_id: 9, modification_ids: [], base: 6, quality: "m7"},
  {chord_base_id: 7, modification_ids: [], base: 4, quality: "7"},
  {chord_base_id: 3, modification_ids: [5], base: 9, quality: "sus4"},
  {chord_base_id: 9, modification_ids: [], base: 4, quality: "m7"},
  {chord_base_id: 4, modification_ids: [], base: 6, quality: "m"},
  {chord_base_id: 4, modification_ids: [], base: 8, quality: "m"},
  {chord_base_id: 7, modification_ids: [], base: 11, quality: "7"},
  {chord_base_id: 3, modification_ids: [], base: 11, quality: ""},
  {chord_base_id: 3, modification_ids: [5], base: 6, quality: "sus4"},
  {chord_base_id: 3, modification_ids: [], base: 12, quality: ""},
  {chord_base_id: 4, modification_ids: [], base: 9, quality: "m"},
  {chord_base_id: 3, modification_ids: [], base: 5, quality: ""},
  {chord_base_id: 3, modification_ids: [], base: 8, quality: ""},
  {chord_base_id: 4, modification_ids: [], base: 10, quality: "m"},
  {chord_base_id: 4, modification_ids: [], base: 12, quality: "m"},
  {chord_base_id: 4, modification_ids: [], base: 2, quality: "m"},
  {chord_base_id: 4, modification_ids: [], base: 7, quality: "m"},
  {chord_base_id: 7, modification_ids: [3], base: 1, quality: "7b5"},
  {chord_base_id: 4, modification_ids: [], base: 3, quality: "m"},
  {chord_base_id: 3, modification_ids: [], base: 3, quality: ""},
  {chord_base_id: 3, modification_ids: [11], base: 2, quality: "add9"},
  {chord_base_id: 7, modification_ids: [], base: 9, quality: "7"},
  {chord_base_id: 3, modification_ids: [11], base: 11, quality: "add9"},
  {chord_base_id: 3, modification_ids: [11], base: 3, quality: "add9"},
  {chord_base_id: 7, modification_ids: [], base: 6, quality: "7"},
  {chord_base_id: 13, modification_ids: [], base: 6, quality: "9"},
  {chord_base_id: 3, modification_ids: [10], base: 4, quality: "add6"},
  {chord_base_id: 8, modification_ids: [], base: 4, quality: "maj7"},
  {chord_base_id: 3, modification_ids: [6], base: 7, quality: "sus2"},
  {chord_base_id: 18, modification_ids: [], base: 4, quality: "m11"},
  {chord_base_id: 3, modification_ids: [5], base: 2, quality: "sus4"},
  {chord_base_id: 3, modification_ids: [5], base: 7, quality: "sus4"},
  {chord_base_id: 3, modification_ids: [7], base: 7, quality: "add2"},
  {chord_base_id: 3, modification_ids: [6], base: 12, quality: "sus2"},
  {chord_base_id: 3, modification_ids: [8], base: 2, quality: "add4"},
  {chord_base_id: 9, modification_ids: [], base: 11, quality: "m7"},
  {chord_base_id: 9, modification_ids: [], base: 7, quality: "m7"},
  {chord_base_id: 7, modification_ids: [], base: 7, quality: "7"},
  {chord_base_id: 9, modification_ids: [], base: 10, quality: "m7"},
  {chord_base_id: 8, modification_ids: [], base: 1, quality: "maj7"},
  {chord_base_id: 7, modification_ids: [], base: 2, quality: "7"},
  {chord_base_id: 9, modification_ids: [], base: 3, quality: "m7"},
  {chord_base_id: 8, modification_ids: [3], base: 1, quality: "maj7b5"},
  {chord_base_id: 8, modification_ids: [], base: 2, quality: "maj7"},
  {chord_base_id: 4, modification_ids: [], base: 5, quality: "m"},
  {chord_base_id: 8, modification_ids: [], base: 7, quality: "maj7"},
  {chord_base_id: 2, modification_ids: [], base: 11, quality: "5"},
  {chord_base_id: 9, modification_ids: [], base: 8, quality: "m7"},
  {chord_base_id: 3, modification_ids: [6], base: 4, quality: "sus2"},
  {chord_base_id: 13, modification_ids: [], base: 7, quality: "9"},
  {chord_base_id: 3, modification_ids: [6], base: 9, quality: "sus2"},
  {chord_base_id: 13, modification_ids: [], base: 9, quality: "9"},
  {chord_base_id: 9, modification_ids: [], base: 1, quality: "m7"},
  {chord_base_id: 3, modification_ids: [6], base: 2, quality: "sus2"},
  {chord_base_id: 9, modification_ids: [], base: 2, quality: "m7"},
  {chord_base_id: 2, modification_ids: [], base: 2, quality: "5"},
  {chord_base_id: 2, modification_ids: [], base: 9, quality: "5"},
  {chord_base_id: 3, modification_ids: [11], base: 7, quality: "add9"},
  {chord_base_id: 8, modification_ids: [], base: 12, quality: "maj7"},
  {chord_base_id: 15, modification_ids: [], base: 12, quality: "maj9"},
  {chord_base_id: 21, modification_ids: [], base: 12, quality: "maj13"},
  {chord_base_id: 3, modification_ids: [], base: 10, quality: ""},
  {chord_base_id: 3, modification_ids: [6], base: 1, quality: "sus2"},
  {chord_base_id: 3, modification_ids: [5], base: 1, quality: "sus4"},
  {chord_base_id: 7, modification_ids: [], base: 8, quality: "7"},
  {chord_base_id: 8, modification_ids: [], base: 9, quality: "maj7"},
  {chord_base_id: 2, modification_ids: [], base: 4, quality: "5"},
  {chord_base_id: 3, modification_ids: [6], base: 8, quality: "sus2"},
  {chord_base_id: 8, modification_ids: [], base: 10, quality: "maj7"},
  {chord_base_id: 9, modification_ids: [], base: 9, quality: "m7"},
  {chord_base_id: 21, modification_ids: [], base: 6, quality: "maj13"},
  {chord_base_id: 3, modification_ids: [11], base: 1, quality: "add9"},
  {chord_base_id: 8, modification_ids: [], base: 6, quality: "maj7"},
  {chord_base_id: 4, modification_ids: [10], base: 6, quality: "madd6"},
  {chord_base_id: 14, modification_ids: [], base: 3, quality: "m9"},
  {chord_base_id: 5, modification_ids: [], base: 9, quality: "dim"},
  {chord_base_id: 7, modification_ids: [], base: 3, quality: "7"},
  {chord_base_id: 7, modification_ids: [], base: 1, quality: "7"},
  {chord_base_id: 5, modification_ids: [], base: 11, quality: "dim"},
  {chord_base_id: 9, modification_ids: [], base: 5, quality: "m7"},
  {chord_base_id: 7, modification_ids: [], base: 10, quality: "7"},
  {chord_base_id: 5, modification_ids: [], base: 4, quality: "dim"},
  {chord_base_id: 5, modification_ids: [], base: 12, quality: "dim"},
  {chord_base_id: 6, modification_ids: [], base: 4, quality: "aug"},
  {chord_base_id: 5, modification_ids: [], base: 5, quality: "dim"},
  {chord_base_id: 7, modification_ids: [5], base: 4, quality: "7sus4"},
  {chord_base_id: 5, modification_ids: [], base: 6, quality: "dim"},
  {chord_base_id: 4, modification_ids: [10], base: 9, quality: "madd6"},
  {chord_base_id: 10, modification_ids: [], base: 9, quality: "dim7"},
  {chord_base_id: 10, modification_ids: [], base: 1, quality: "dim7"},
  {chord_base_id: 8, modification_ids: [], base: 8, quality: "maj7"},
  {chord_base_id: 7, modification_ids: [6], base: 9, quality: "7sus2"},
  {chord_base_id: 3, modification_ids: [6], base: 5, quality: "sus2"},
  {chord_base_id: 7, modification_ids: [], base: 12, quality: "7"},
  {chord_base_id: 2, modification_ids: [], base: 1, quality: "5"},
  {chord_base_id: 3, modification_ids: [5], base: 8, quality: "sus4"},
  {chord_base_id: 7, modification_ids: [], base: 5, quality: "7"},
  {chord_base_id: 3, modification_ids: [10], base: 2, quality: "add6"},
  {chord_base_id: 3, modification_ids: [11], base: 9, quality: "add9"},
  {chord_base_id: 5, modification_ids: [], base: 7, quality: "dim"},
  {chord_base_id: 3, modification_ids: [10], base: 12, quality: "add6"},
  {chord_base_id: 3, modification_ids: [5], base: 4, quality: "sus4"},
  {chord_base_id: 2, modification_ids: [], base: 10, quality: "5"},
  {chord_base_id: 2, modification_ids: [], base: 8, quality: "5"},
  {chord_base_id: 3, modification_ids: [5], base: 11, quality: "sus4"},
  {chord_base_id: 3, modification_ids: [5], base: 12, quality: "sus4"},
  {chord_base_id: 8, modification_ids: [], base: 5, quality: "maj7"},
  {chord_base_id: 10, modification_ids: [], base: 8, quality: "dim7"},
  {chord_base_id: 18, modification_ids: [], base: 10, quality: "m11"},
  {chord_base_id: 13, modification_ids: [], base: 1, quality: "9"},
  {chord_base_id: 6, modification_ids: [], base: 9, quality: "aug"},
  {chord_base_id: 7, modification_ids: [5], base: 8, quality: "7sus4"},
  {chord_base_id: 10, modification_ids: [], base: 7, quality: "dim7"},
  {chord_base_id: 2, modification_ids: [], base: 6, quality: "5"},
  {chord_base_id: 19, modification_ids: [], base: 11, quality: "13"},
  {chord_base_id: 3, modification_ids: [5], base: 5, quality: "sus4"},
  {chord_base_id: 3, modification_ids: [10], base: 11, quality: "add6"},
  {chord_base_id: 3, modification_ids: [6], base: 6, quality: "sus2"},
  {chord_base_id: 7, modification_ids: [5], base: 5, quality: "7sus4"},
  {chord_base_id: 3, modification_ids: [10], base: 9, quality: "add6"},
  {chord_base_id: 14, modification_ids: [], base: 6, quality: "m9"},
  {chord_base_id: 4, modification_ids: [10], base: 2, quality: "madd6"},
  {chord_base_id: 7, modification_ids: [3], base: 2, quality: "7b5"},
  {chord_base_id: 7, modification_ids: [3], base: 6, quality: "7b5"},
  {chord_base_id: 7, modification_ids: [3], base: 7, quality: "7b5"},
  {chord_base_id: 3, modification_ids: [5], base: 10, quality: "sus4"},
  {chord_base_id: 2, modification_ids: [], base: 5, quality: "5"},
  {chord_base_id: 3, modification_ids: [11], base: 12, quality: "add9"},
  {chord_base_id: 3, modification_ids: [7], base: 6, quality: "add2"},
  {chord_base_id: 4, modification_ids: [10], base: 3, quality: "madd6"},
  {chord_base_id: 3, modification_ids: [7], base: 8, quality: "add2"},
  {chord_base_id: 18, modification_ids: [], base: 3, quality: "m11"},
  {chord_base_id: 18, modification_ids: [], base: 7, quality: "m11"},
  {chord_base_id: 21, modification_ids: [], base: 11, quality: "maj13"},
  {chord_base_id: 3, modification_ids: [10], base: 1, quality: "add6"},
  {chord_base_id: 5, modification_ids: [], base: 2, quality: "dim"},
  {chord_base_id: 8, modification_ids: [], base: 11, quality: "maj7"},
  {chord_base_id: 7, modification_ids: [3], base: 11, quality: "7b5"},
  {chord_base_id: 7, modification_ids: [3], base: 10, quality: "7b5"},
  {chord_base_id: 4, modification_ids: [14], base: 4, quality: "madd13"},
  {chord_base_id: 9, modification_ids: [12], base: 2, quality: "m7add11"},
  {chord_base_id: 5, modification_ids: [], base: 3, quality: "dim"},
  {chord_base_id: 2, modification_ids: [], base: 3, quality: "5"},
  {chord_base_id: 9, modification_ids: [8], base: 4, quality: "m7add4"},
  {chord_base_id: 7, modification_ids: [4], base: 8, quality: "7b9"},
  {chord_base_id: 6, modification_ids: [], base: 8, quality: "aug"},
  {chord_base_id: 4, modification_ids: [10], base: 4, quality: "madd6"},
  {chord_base_id: 8, modification_ids: [3], base: 9, quality: "maj7b5"},
  {chord_base_id: 15, modification_ids: [], base: 6, quality: "maj9"},
  {chord_base_id: 5, modification_ids: [], base: 1, quality: "dim"},
  {chord_base_id: 3, modification_ids: [11], base: 8, quality: "add9"},
  {chord_base_id: 3, modification_ids: [6], base: 10, quality: "sus2"},
  {chord_base_id: 3, modification_ids: [10], base: 7, quality: "add6"},
  {chord_base_id: 3, modification_ids: [7], base: 3, quality: "add2"},
  {chord_base_id: 3, modification_ids: [7], base: 1, quality: "add2"},
  {chord_base_id: 8, modification_ids: [5], base: 2, quality: "maj7sus4"},
  {chord_base_id: 2, modification_ids: [], base: 12, quality: "5"},
  {chord_base_id: 2, modification_ids: [], base: 7, quality: "5"},
  {chord_base_id: 3, modification_ids: [10], base: 8, quality: "add6"},
  {chord_base_id: 15, modification_ids: [], base: 8, quality: "maj9"},
  {chord_base_id: 9, modification_ids: [], base: 12, quality: "m7"},
  {chord_base_id: 3, modification_ids: [6], base: 3, quality: "sus2"},
  {chord_base_id: 14, modification_ids: [], base: 2, quality: "m9"},
  {chord_base_id: 9, modification_ids: [3], base: 2, quality: "m7b5"},
  {chord_base_id: 3, modification_ids: [11], base: 6, quality: "add9"},
  {chord_base_id: 3, modification_ids: [10], base: 6, quality: "add6"},
  {chord_base_id: 7, modification_ids: [5], base: 2, quality: "7sus4"},
  {chord_base_id: 3, modification_ids: [8], base: 1, quality: "add4"},
  {chord_base_id: 9, modification_ids: [8], base: 5, quality: "m7add4"},
  {chord_base_id: 9, modification_ids: [8], base: 10, quality: "m7add4"},
  {chord_base_id: 13, modification_ids: [], base: 3, quality: "9"},
  {chord_base_id: 13, modification_ids: [], base: 8, quality: "9"},
  {chord_base_id: 10, modification_ids: [], base: 4, quality: "dim7"},
  {chord_base_id: 10, modification_ids: [], base: 11, quality: "dim7"},
  {chord_base_id: 9, modification_ids: [3], base: 12, quality: "m7b5"},
  {chord_base_id: 10, modification_ids: [], base: 3, quality: "dim7"},
  {chord_base_id: 13, modification_ids: [], base: 11, quality: "9"},
  {chord_base_id: 13, modification_ids: [], base: 10, quality: "9"},
  {chord_base_id: 9, modification_ids: [8], base: 3, quality: "m7add4"},
  {chord_base_id: 10, modification_ids: [], base: 6, quality: "dim7"},
  {chord_base_id: 9, modification_ids: [8], base: 12, quality: "m7add4"},
  {chord_base_id: 10, modification_ids: [], base: 12, quality: "dim7"},
  {chord_base_id: 10, modification_ids: [], base: 2, quality: "dim7"},
  {chord_base_id: 3, modification_ids: [10], base: 3, quality: "add6"},
  {chord_base_id: 13, modification_ids: [], base: 2, quality: "9"},
  {chord_base_id: 3, modification_ids: [10], base: 10, quality: "add6"},
  {chord_base_id: 13, modification_ids: [], base: 12, quality: "9"},
  {chord_base_id: 4, modification_ids: [8], base: 12, quality: "madd4"},
  {chord_base_id: 7, modification_ids: [3], base: 8, quality: "7b5"},
  {chord_base_id: 6, modification_ids: [], base: 12, quality: "aug"},
  {chord_base_id: 3, modification_ids: [10], base: 5, quality: "add6"},
  {chord_base_id: 9, modification_ids: [3], base: 11, quality: "m7b5"},
  {chord_base_id: 9, modification_ids: [3], base: 7, quality: "m7b5"},
  {chord_base_id: 13, modification_ids: [], base: 5, quality: "9"},
  {chord_base_id: 6, modification_ids: [], base: 5, quality: "aug"},
  {chord_base_id: 10, modification_ids: [], base: 5, quality: "dim7"},
  {chord_base_id: 7, modification_ids: [5], base: 10, quality: "7sus4"},
  {chord_base_id: 15, modification_ids: [], base: 1, quality: "maj9"},
  {chord_base_id: 15, modification_ids: [], base: 3, quality: "maj9"},
  {chord_base_id: 15, modification_ids: [], base: 7, quality: "maj9"},
  {chord_base_id: 4, modification_ids: [11], base: 5, quality: "madd9"},
  {chord_base_id: 7, modification_ids: [3], base: 5, quality: "7b5"},
  {chord_base_id: 15, modification_ids: [], base: 11, quality: "maj9"},
  {chord_base_id: 15, modification_ids: [], base: 2, quality: "maj9"},
  {chord_base_id: 6, modification_ids: [], base: 1, quality: "aug"},
  {chord_base_id: 7, modification_ids: [3], base: 3, quality: "7b5"},
  {chord_base_id: 7, modification_ids: [5], base: 11, quality: "7sus4"},
  {chord_base_id: 4, modification_ids: [10], base: 11, quality: "madd6"},
  {chord_base_id: 3, modification_ids: [5], base: 3, quality: "sus4"},
  {chord_base_id: 7, modification_ids: [5], base: 9, quality: "7sus4"},
  {chord_base_id: 4, modification_ids: [10], base: 5, quality: "madd6"},
  {chord_base_id: 14, modification_ids: [], base: 4, quality: "m9"},
  {chord_base_id: 16, modification_ids: [], base: 7, quality: "11"},
  {chord_base_id: 18, modification_ids: [], base: 9, quality: "m11"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 2, quality: "add4add9"},
  {chord_base_id: 7, modification_ids: [3], base: 9, quality: "7b5"},
  {chord_base_id: 4, modification_ids: [10], base: 7, quality: "madd6"},
  {chord_base_id: 5, modification_ids: [], base: 8, quality: "dim"},
  {chord_base_id: 5, modification_ids: [], base: 10, quality: "dim"},
  {chord_base_id: 19, modification_ids: [], base: 8, quality: "13"},
  {chord_base_id: 9, modification_ids: [3], base: 3, quality: "m7b5"},
  {chord_base_id: 16, modification_ids: [], base: 1, quality: "11"},
  {chord_base_id: 8, modification_ids: [5], base: 9, quality: "maj7sus4"},
  {chord_base_id: 14, modification_ids: [], base: 5, quality: "m9"},
  {chord_base_id: 14, modification_ids: [], base: 10, quality: "m9"},
  {chord_base_id: 14, modification_ids: [], base: 12, quality: "m9"},
  {chord_base_id: 6, modification_ids: [], base: 7, quality: "aug"},
  {chord_base_id: 6, modification_ids: [], base: 2, quality: "aug"},
  {chord_base_id: 3, modification_ids: [7], base: 12, quality: "add2"},
  {chord_base_id: 18, modification_ids: [], base: 2, quality: "m11"},
  {chord_base_id: 18, modification_ids: [], base: 12, quality: "m11"},
  {chord_base_id: 8, modification_ids: [], base: 3, quality: "maj7"},
  {chord_base_id: 13, modification_ids: [5], base: 8, quality: "9sus4"},
  {chord_base_id: 3, modification_ids: [8], base: 7, quality: "add4"},
  {chord_base_id: 3, modification_ids: [11], base: 5, quality: "add9"},
  {chord_base_id: 19, modification_ids: [], base: 1, quality: "13"},
  {chord_base_id: 18, modification_ids: [], base: 5, quality: "m11"},
  {chord_base_id: 15, modification_ids: [], base: 9, quality: "maj9"},
  {chord_base_id: 14, modification_ids: [], base: 8, quality: "m9"},
  {chord_base_id: 19, modification_ids: [4], base: 1, quality: "13b9"},
  {chord_base_id: 13, modification_ids: [3], base: 11, quality: "9b5"},
  {chord_base_id: 13, modification_ids: [5], base: 3, quality: "9sus4"},
  {chord_base_id: 13, modification_ids: [5], base: 4, quality: "9sus4"},
  {chord_base_id: 9, modification_ids: [13], base: 12, quality: "m7addb13"},
  {chord_base_id: 6, modification_ids: [], base: 11, quality: "aug"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 7, quality: "sus2add6"},
  {chord_base_id: 8, modification_ids: [6], base: 5, quality: "maj7sus2"},
  {chord_base_id: 16, modification_ids: [], base: 11, quality: "11"},
  {chord_base_id: 7, modification_ids: [5], base: 7, quality: "7sus4"},
  {chord_base_id: 3, modification_ids: [8], base: 9, quality: "add4"},
  {chord_base_id: 16, modification_ids: [], base: 6, quality: "11"},
  {chord_base_id: 16, modification_ids: [], base: 10, quality: "11"},
  {chord_base_id: 14, modification_ids: [], base: 9, quality: "m9"},
  {chord_base_id: 10, modification_ids: [], base: 10, quality: "dim7"},
  {chord_base_id: 7, modification_ids: [5], base: 12, quality: "7sus4"},
  {chord_base_id: 7, modification_ids: [6], base: 2, quality: "7sus2"},
  {chord_base_id: 4, modification_ids: [10], base: 8, quality: "madd6"},
  {chord_base_id: 4, modification_ids: [10], base: 10, quality: "madd6"},
  {chord_base_id: 7, modification_ids: [6], base: 7, quality: "7sus2"},
  {chord_base_id: 15, modification_ids: [], base: 4, quality: "maj9"},
  {chord_base_id: 19, modification_ids: [], base: 7, quality: "13"},
  {chord_base_id: 19, modification_ids: [], base: 10, quality: "13"},
  {chord_base_id: 15, modification_ids: [], base: 5, quality: "maj9"},
  {chord_base_id: 9, modification_ids: [3], base: 6, quality: "m7b5"},
  {chord_base_id: 3, modification_ids: [11], base: 10, quality: "add9"},
  {chord_base_id: 3, modification_ids: [8], base: 8, quality: "add4"},
  {chord_base_id: 4, modification_ids: [11], base: 3, quality: "madd9"},
  {chord_base_id: 7, modification_ids: [5], base: 3, quality: "7sus4"},
  {chord_base_id: 7, modification_ids: [5], base: 6, quality: "7sus4"},
  {chord_base_id: 8, modification_ids: [14], base: 11, quality: "maj7add13"},
  {chord_base_id: 6, modification_ids: [], base: 3, quality: "aug"},
  {chord_base_id: 7, modification_ids: [3], base: 12, quality: "7b5"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 7, quality: "add4add9"},
  {chord_base_id: 4, modification_ids: [11], base: 9, quality: "madd9"},
  {chord_base_id: 7, modification_ids: [4], base: 2, quality: "7b9"},
  {chord_base_id: 7, modification_ids: [13], base: 5, quality: "7addb13"},
  {chord_base_id: 3, modification_ids: [6], base: 11, quality: "sus2"},
  {chord_base_id: 18, modification_ids: [], base: 11, quality: "m11"},
  {chord_base_id: 3, modification_ids: [12], base: 12, quality: "add11"},
  {chord_base_id: 7, modification_ids: [5], base: 1, quality: "7sus4"},
  {chord_base_id: 21, modification_ids: [], base: 1, quality: "maj13"},
  {chord_base_id: 13, modification_ids: [3], base: 2, quality: "9b5"},
  {chord_base_id: 21, modification_ids: [], base: 9, quality: "maj13"},
  {chord_base_id: 19, modification_ids: [], base: 6, quality: "13"},
  {chord_base_id: 4, modification_ids: [12], base: 4, quality: "madd11"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 12, quality: "add6add9"},
  {chord_base_id: 9, modification_ids: [3], base: 8, quality: "m7b5"},
  {chord_base_id: 4, modification_ids: [12], base: 10, quality: "madd11"},
  {chord_base_id: 14, modification_ids: [], base: 11, quality: "m9"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 5, quality: "add6add9"},
  {chord_base_id: 9, modification_ids: [8], base: 9, quality: "m7add4"},
  {chord_base_id: 3, modification_ids: [7], base: 5, quality: "add2"},
  {chord_base_id: 13, modification_ids: [], base: 4, quality: "9"},
  {chord_base_id: 7, modification_ids: [4], base: 5, quality: "7b9"},
  {chord_base_id: 13, modification_ids: [5], base: 5, quality: "9sus4"},
  {chord_base_id: 3, modification_ids: [12], base: 7, quality: "add11"},
  {chord_base_id: 18, modification_ids: [], base: 1, quality: "m11"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 2, quality: "sus2add6"},
  {chord_base_id: 8, modification_ids: [6], base: 12, quality: "maj7sus2"},
  {chord_base_id: 7, modification_ids: [6], base: 8, quality: "7sus2"},
  {chord_base_id: 8, modification_ids: [6], base: 7, quality: "maj7sus2"},
  {chord_base_id: 16, modification_ids: [], base: 2, quality: "11"},
  {chord_base_id: 3, modification_ids: [7], base: 10, quality: "add2"},
  {chord_base_id: 3, modification_ids: [8], base: 5, quality: "add4"},
  {chord_base_id: 7, modification_ids: [8], base: 9, quality: "7add4"},
  {chord_base_id: 3, modification_ids: [12], base: 5, quality: "add11"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 5, quality: "sus2add6"},
  {chord_base_id: 14, modification_ids: [], base: 1, quality: "m9"},
  {chord_base_id: 15, modification_ids: [], base: 10, quality: "maj9"},
  {chord_base_id: 7, modification_ids: [10], base: 3, quality: "7add6"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 11, quality: "add6add9"},
  {chord_base_id: 9, modification_ids: [3], base: 5, quality: "m7b5"},
  {chord_base_id: 19, modification_ids: [], base: 9, quality: "13"},
  {chord_base_id: 7, modification_ids: [13], base: 10, quality: "7addb13"},
  {chord_base_id: 6, modification_ids: [], base: 6, quality: "aug"},
  {chord_base_id: 21, modification_ids: [], base: 2, quality: "maj13"},
  {chord_base_id: 4, modification_ids: [11], base: 10, quality: "madd9"},
  {chord_base_id: 19, modification_ids: [], base: 3, quality: "13"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 7, quality: "sus4add6"},
  {chord_base_id: 21, modification_ids: [], base: 8, quality: "maj13"},
  {chord_base_id: 4, modification_ids: [10], base: 1, quality: "madd6"},
  {chord_base_id: 13, modification_ids: [5], base: 1, quality: "9sus4"},
  {chord_base_id: 6, modification_ids: [], base: 10, quality: "aug"},
  {chord_base_id: 20, modification_ids: [], base: 6, quality: "m13"},
  {chord_base_id: 18, modification_ids: [], base: 6, quality: "m11"},
  {chord_base_id: 3, modification_ids: [8], base: 11, quality: "add4"},
  {chord_base_id: 3, modification_ids: [8], base: 12, quality: "add4"},
  {chord_base_id: 9, modification_ids: [3], base: 10, quality: "m7b5"},
  {chord_base_id: 9, modification_ids: [3], base: 1, quality: "m7b5"},
  {chord_base_id: 7, modification_ids: [14], base: 8, quality: "7add13"},
  {chord_base_id: 7, modification_ids: [4], base: 10, quality: "7b9"},
  {chord_base_id: 9, modification_ids: [3], base: 4, quality: "m7b5"},
  {chord_base_id: 16, modification_ids: [], base: 5, quality: "11"},
  {chord_base_id: 16, modification_ids: [], base: 12, quality: "11"},
  {chord_base_id: 14, modification_ids: [], base: 7, quality: "m9"},
  {chord_base_id: 3, modification_ids: [8], base: 10, quality: "add4"},
  {chord_base_id: 4, modification_ids: [11], base: 7, quality: "madd9"},
  {chord_base_id: 8, modification_ids: [6], base: 1, quality: "maj7sus2"},
  {chord_base_id: 16, modification_ids: [], base: 9, quality: "11"},
  {chord_base_id: 16, modification_ids: [], base: 4, quality: "11"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 1, quality: "sus2add6"},
  {chord_base_id: 13, modification_ids: [5], base: 11, quality: "9sus4"},
  {chord_base_id: 9, modification_ids: [12], base: 4, quality: "m7add11"},
  {chord_base_id: 21, modification_ids: [], base: 10, quality: "maj13"},
  {chord_base_id: 7, modification_ids: [13], base: 7, quality: "7addb13"},
  {chord_base_id: 7, modification_ids: [13], base: 3, quality: "7addb13"},
  {chord_base_id: 19, modification_ids: [4], base: 8, quality: "13b9"},
  {chord_base_id: 7, modification_ids: [4], base: 1, quality: "7b9"},
  {chord_base_id: 4, modification_ids: [12], base: 6, quality: "madd11"},
  {chord_base_id: 9, modification_ids: [8], base: 8, quality: "m7add4"},
  {chord_base_id: 7, modification_ids: [4], base: 4, quality: "7b9"},
  {chord_base_id: 4, modification_ids: [10], base: 12, quality: "madd6"},
  {chord_base_id: 19, modification_ids: [], base: 5, quality: "13"},
  {chord_base_id: 9, modification_ids: [3], base: 9, quality: "m7b5"},
  {chord_base_id: 9, modification_ids: [14], base: 11, quality: "m7add13"},
  {chord_base_id: 7, modification_ids: [4], base: 12, quality: "7b9"},
  {chord_base_id: 16, modification_ids: [], base: 8, quality: "11"},
  {chord_base_id: 7, modification_ids: [6], base: 12, quality: "7sus2"},
  {chord_base_id: 7, modification_ids: [4], base: 7, quality: "7b9"},
  {chord_base_id: 4, modification_ids: [12], base: 9, quality: "madd11"},
  {chord_base_id: 7, modification_ids: [12], base: 2, quality: "7add11"},
  {chord_base_id: 18, modification_ids: [], base: 8, quality: "m11"},
  {chord_base_id: 3, modification_ids: [7], base: 11, quality: "add2"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 10, quality: "add6add9"},
  {chord_base_id: 19, modification_ids: [], base: 2, quality: "13"},
  {chord_base_id: 9, modification_ids: [12], base: 10, quality: "m7add11"},
  {chord_base_id: 21, modification_ids: [], base: 5, quality: "maj13"},
  {chord_base_id: 9, modification_ids: [1], base: 7, quality: "m7no5"},
  {chord_base_id: 3, modification_ids: [12], base: 10, quality: "add11"},
  {chord_base_id: 13, modification_ids: [3], base: 6, quality: "9b5"},
  {chord_base_id: 8, modification_ids: [3], base: 6, quality: "maj7b5"},
  {chord_base_id: 19, modification_ids: [], base: 12, quality: "13"},
  {chord_base_id: 13, modification_ids: [5], base: 6, quality: "9sus4"},
  {chord_base_id: 19, modification_ids: [], base: 4, quality: "13"},
  {chord_base_id: 21, modification_ids: [], base: 7, quality: "maj13"},
  {chord_base_id: 13, modification_ids: [6], base: 3, quality: "9sus2"},
  {chord_base_id: 9, modification_ids: [12], base: 9, quality: "m7add11"},
  {chord_base_id: 4, modification_ids: [11], base: 8, quality: "madd9"},
  {chord_base_id: 3, modification_ids: [8, 10], base: 10, quality: "add4add6"},
  {chord_base_id: 7, modification_ids: [6], base: 5, quality: "7sus2"},
  {chord_base_id: 13, modification_ids: [5], base: 7, quality: "9sus4"},
  {chord_base_id: 7, modification_ids: [10], base: 8, quality: "7add6"},
  {chord_base_id: 8, modification_ids: [14], base: 3, quality: "maj7add13"},
  {chord_base_id: 8, modification_ids: [6], base: 6, quality: "maj7sus2"},
  {chord_base_id: 4, modification_ids: [8], base: 7, quality: "madd4"},
  {chord_base_id: 3, modification_ids: [11, 5], base: 10, quality: "sus4add9"},
  {chord_base_id: 4, modification_ids: [11], base: 12, quality: "madd9"},
  {chord_base_id: 7, modification_ids: [3], base: 4, quality: "7b5"},
  {chord_base_id: 4, modification_ids: [12], base: 5, quality: "madd11"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 3, quality: "sus4add6"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 6, quality: "sus2add6"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 6, quality: "sus4add6"},
  {chord_base_id: 3, modification_ids: [8, 10], base: 3, quality: "add4add6"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 10, quality: "sus2add6"},
  {chord_base_id: 7, modification_ids: [17, 5], base: 5, quality: "7sus4addb9"},
  {chord_base_id: 7, modification_ids: [10], base: 12, quality: "7add6"},
  {chord_base_id: 7, modification_ids: [10], base: 4, quality: "7add6"},
  {chord_base_id: 3, modification_ids: [8], base: 6, quality: "add4"},
  {chord_base_id: 3, modification_ids: [12], base: 8, quality: "add11"},
  {chord_base_id: 4, modification_ids: [12], base: 8, quality: "madd11"},
  {chord_base_id: 3, modification_ids: [10, 12], base: 1, quality: "add6add11"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 3, quality: "add4add9"},
  {chord_base_id: 7, modification_ids: [12], base: 9, quality: "7add11"},
  {chord_base_id: 4, modification_ids: [7], base: 12, quality: "madd2"},
  {chord_base_id: 7, modification_ids: [4], base: 3, quality: "7b9"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 12, quality: "sus4add6"},
  {chord_base_id: 7, modification_ids: [6], base: 1, quality: "7sus2"},
  {chord_base_id: 3, modification_ids: [12], base: 3, quality: "add11"},
  {chord_base_id: 3, modification_ids: [8], base: 3, quality: "add4"},
  {chord_base_id: 7, modification_ids: [12], base: 10, quality: "7add11"},
  {chord_base_id: 17, modification_ids: [], base: 2, quality: "maj11"},
  {chord_base_id: 7, modification_ids: [6], base: 11, quality: "7sus2"},
  {chord_base_id: 3, modification_ids: [12], base: 6, quality: "add11"},
  {chord_base_id: 8, modification_ids: [6], base: 11, quality: "maj7sus2"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 8, quality: "add4add9"},
  {chord_base_id: 7, modification_ids: [6], base: 3, quality: "7sus2"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 2, quality: "add6add9"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 3, quality: "add6add9"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 1, quality: "add6add9"},
  {chord_base_id: 7, modification_ids: [6], base: 10, quality: "7sus2"},
  {chord_base_id: 3, modification_ids: [12], base: 1, quality: "add11"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 8, quality: "sus2add6"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 8, quality: "sus4add6"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 1, quality: "sus4add6"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 4, quality: "sus4add6"},
  {chord_base_id: 8, modification_ids: [5], base: 4, quality: "maj7sus4"},
  {chord_base_id: 13, modification_ids: [5], base: 2, quality: "9sus4"},
  {chord_base_id: 19, modification_ids: [4], base: 12, quality: "13b9"},
  {chord_base_id: 3, modification_ids: [11], base: 4, quality: "add9"},
  {chord_base_id: 4, modification_ids: [11], base: 6, quality: "madd9"},
  {chord_base_id: 4, modification_ids: [9], base: 10, quality: "maddb6"},
  {chord_base_id: 7, modification_ids: [12], base: 3, quality: "7add11"},
  {chord_base_id: 7, modification_ids: [8], base: 8, quality: "7add4"},
  {chord_base_id: 4, modification_ids: [12], base: 3, quality: "madd11"},
  {chord_base_id: 3, modification_ids: [14], base: 6, quality: "add13"},
  {chord_base_id: 3, modification_ids: [12], base: 11, quality: "add11"},
  {chord_base_id: 8, modification_ids: [14], base: 9, quality: "maj7add13"},
  {chord_base_id: 8, modification_ids: [5], base: 6, quality: "maj7sus4"},
  {chord_base_id: 8, modification_ids: [5], base: 1, quality: "maj7sus4"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 11, quality: "sus2add6"},
  {chord_base_id: 4, modification_ids: [8], base: 10, quality: "madd4"},
  {chord_base_id: 7, modification_ids: [6], base: 6, quality: "7sus2"},
  {chord_base_id: 8, modification_ids: [6], base: 9, quality: "maj7sus2"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 11, quality: "sus4add6"},
  {chord_base_id: 9, modification_ids: [12], base: 3, quality: "m7add11"},
  {chord_base_id: 3, modification_ids: [12], base: 4, quality: "add11"},
  {chord_base_id: 4, modification_ids: [11], base: 1, quality: "madd9"},
  {chord_base_id: 4, modification_ids: [8], base: 3, quality: "madd4"},
  {chord_base_id: 7, modification_ids: [13], base: 8, quality: "7addb13"},
  {chord_base_id: 4, modification_ids: [8], base: 1, quality: "madd4"},
  {chord_base_id: 3, modification_ids: [8], base: 4, quality: "add4"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 1, quality: "add4add9"},
  {chord_base_id: 4, modification_ids: [11], base: 11, quality: "madd9"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 9, quality: "sus4add6"},
  {chord_base_id: 13, modification_ids: [5], base: 9, quality: "9sus4"},
  {chord_base_id: 16, modification_ids: [], base: 3, quality: "11"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 4, quality: "add6add9"},
  {chord_base_id: 7, modification_ids: [4], base: 6, quality: "7b9"},
  {chord_base_id: 20, modification_ids: [], base: 5, quality: "m13"},
  {chord_base_id: 7, modification_ids: [6], base: 4, quality: "7sus2"},
  {chord_base_id: 4, modification_ids: [8], base: 6, quality: "madd4"},
  {chord_base_id: 20, modification_ids: [], base: 10, quality: "m13"},
  {chord_base_id: 20, modification_ids: [], base: 3, quality: "m13"},
  {chord_base_id: 3, modification_ids: [12], base: 9, quality: "add11"},
  {chord_base_id: 3, modification_ids: [7, 6], base: 4, quality: "sus2add2"},
  {chord_base_id: 13, modification_ids: [5], base: 10, quality: "9sus4"},
  {chord_base_id: 8, modification_ids: [6], base: 4, quality: "maj7sus2"},
  {chord_base_id: 8, modification_ids: [6], base: 2, quality: "maj7sus2"},
  {chord_base_id: 19, modification_ids: [4], base: 9, quality: "13b9"},
  {chord_base_id: 9, modification_ids: [8], base: 11, quality: "m7add4"},
  {chord_base_id: 3, modification_ids: [12, 6], base: 3, quality: "sus2add11"},
  {chord_base_id: 3, modification_ids: [14, 5], base: 1, quality: "sus4add13"},
  {chord_base_id: 3, modification_ids: [7], base: 9, quality: "add2"},
  {chord_base_id: 3, modification_ids: [7], base: 2, quality: "add2"},
  {chord_base_id: 4, modification_ids: [12], base: 1, quality: "madd11"},
  {chord_base_id: 7, modification_ids: [2], base: 3, quality: "7no3"},
  {chord_base_id: 8, modification_ids: [2], base: 3, quality: "maj7no3"},
  {chord_base_id: 13, modification_ids: [2], base: 3, quality: "9no3"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 2, quality: "sus4add6"},
  {chord_base_id: 13, modification_ids: [3], base: 1, quality: "9b5"},
  {chord_base_id: 21, modification_ids: [], base: 4, quality: "maj13"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 9, quality: "sus2add6"},
  {chord_base_id: 7, modification_ids: [12], base: 1, quality: "7add11"},
  {chord_base_id: 3, modification_ids: [12, 6], base: 11, quality: "sus2add11"},
  {chord_base_id: 7, modification_ids: [8], base: 3, quality: "7add4"},
  {chord_base_id: 7, modification_ids: [8], base: 4, quality: "7add4"},
  {chord_base_id: 3, modification_ids: [8, 10], base: 7, quality: "add4add6"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 4, quality: "sus2add6"},
  {chord_base_id: 3, modification_ids: [10, 12], base: 7, quality: "add6add11"},
  {chord_base_id: 7, modification_ids: [12], base: 11, quality: "7add11"},
  {chord_base_id: 4, modification_ids: [6], base: 6, quality: "msus2"},
  {chord_base_id: 20, modification_ids: [], base: 1, quality: "m13"},
  {chord_base_id: 8, modification_ids: [12], base: 10, quality: "maj7add11"},
  {chord_base_id: 3, modification_ids: [10, 12], base: 5, quality: "add6add11"},
  {chord_base_id: 4, modification_ids: [17], base: 1, quality: "maddb9"},
  {chord_base_id: 20, modification_ids: [], base: 9, quality: "m13"},
  {chord_base_id: 8, modification_ids: [3], base: 8, quality: "maj7b5"},
  {chord_base_id: 9, modification_ids: [14], base: 12, quality: "m7add13"},
  {chord_base_id: 4, modification_ids: [8], base: 5, quality: "madd4"},
  {chord_base_id: 8, modification_ids: [6], base: 8, quality: "maj7sus2"},
  {chord_base_id: 3, modification_ids: [7], base: 4, quality: "add2"},
  {chord_base_id: 3, modification_ids: [10, 5], base: 10, quality: "sus4add6"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 5, quality: "add4add9"},
  {chord_base_id: 13, modification_ids: [3], base: 10, quality: "9b5"},
  {chord_base_id: 13, modification_ids: [5], base: 12, quality: "9sus4"},
  {chord_base_id: 4, modification_ids: [12], base: 7, quality: "madd11"},
  {chord_base_id: 17, modification_ids: [], base: 8, quality: "maj11"},
  {chord_base_id: 9, modification_ids: [12], base: 6, quality: "m7add11"},
  {chord_base_id: 7, modification_ids: [4], base: 11, quality: "7b9"},
  {chord_base_id: 7, modification_ids: [4], base: 9, quality: "7b9"},
  {chord_base_id: 21, modification_ids: [], base: 3, quality: "maj13"},
  {chord_base_id: 4, modification_ids: [10, 11], base: 5, quality: "madd6add9"},
  {chord_base_id: 9, modification_ids: [12], base: 7, quality: "m7add11"},
  {chord_base_id: 20, modification_ids: [], base: 12, quality: "m13"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 6, quality: "add6add9"},
  {chord_base_id: 8, modification_ids: [14], base: 4, quality: "maj7add13"},
  {chord_base_id: 20, modification_ids: [], base: 8, quality: "m13"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 3, quality: "sus2add6"},
  {chord_base_id: 4, modification_ids: [10, 11], base: 8, quality: "madd6add9"},
  {chord_base_id: 9, modification_ids: [8], base: 1, quality: "m7add4"},
  {chord_base_id: 7, modification_ids: [2], base: 1, quality: "7no3"},
  {chord_base_id: 17, modification_ids: [], base: 1, quality: "maj11"},
  {chord_base_id: 3, modification_ids: [8, 10], base: 8, quality: "add4add6"},
  {chord_base_id: 3, modification_ids: [12], base: 2, quality: "add11"},
  {chord_base_id: 8, modification_ids: [14], base: 1, quality: "maj7add13"},
  {chord_base_id: 3, modification_ids: [10, 6], base: 12, quality: "sus2add6"},
  {chord_base_id: 9, modification_ids: [18], base: 11, quality: "m7addb11"},
  {chord_base_id: 8, modification_ids: [3], base: 12, quality: "maj7b5"},
  {chord_base_id: 3, modification_ids: [8, 10], base: 4, quality: "add4add6"},
  {chord_base_id: 3, modification_ids: [9], base: 3, quality: "addb6"},
  {chord_base_id: 9, modification_ids: [12], base: 8, quality: "m7add11"},
  {chord_base_id: 4, modification_ids: [14], base: 8, quality: "madd13"},
  {chord_base_id: 4, modification_ids: [14], base: 9, quality: "madd13"},
  {chord_base_id: 4, modification_ids: [9], base: 8, quality: "maddb6"},
  {chord_base_id: 3, modification_ids: [9], base: 10, quality: "addb6"},
  {chord_base_id: 4, modification_ids: [10, 11], base: 1, quality: "madd6add9"},
  {chord_base_id: 3, modification_ids: [10, 11], base: 9, quality: "add6add9"},
  {chord_base_id: 7, modification_ids: [10], base: 6, quality: "7add6"},
  {chord_base_id: 7, modification_ids: [10], base: 11, quality: "7add6"},
  {chord_base_id: 3, modification_ids: [10, 12], base: 11, quality: "add6add11"},
  {chord_base_id: 4, modification_ids: [12], base: 11, quality: "madd11"},
  {chord_base_id: 4, modification_ids: [9], base: 9, quality: "maddb6"},
  {chord_base_id: 3, modification_ids: [13], base: 8, quality: "addb13"},
  {chord_base_id: 3, modification_ids: [8, 11], base: 6, quality: "add4add9"},
  {chord_base_id: 9, modification_ids: [12], base: 1, quality: "m7add11"},
  {chord_base_id: 3, modification_ids: [14], base: 4, quality: "add13"},
  {chord_base_id: 3, modification_ids: [10, 12], base: 4, quality: "add6add11"},
  {chord_base_id: 17, modification_ids: [], base: 11, quality: "maj11"},
  {chord_base_id: 1, modification_ids: [], base: 4, quality: "unison"},
  {chord_base_id: 9, modification_ids: [8], base: 6, quality: "m7add4"},
  {chord_base_id: 4, modification_ids: [8], base: 8, quality: "madd4"},
  {chord_base_id: 7, modification_ids: [12], base: 8, quality: "7add11"},
  {chord_base_id: 9, modification_ids: [14], base: 6, quality: "m7add13"},
  {chord_base_id: 4, modification_ids: [6], base: 1, quality: "msus2"},
  {chord_base_id: 7, modification_ids: [10], base: 9, quality: "7add6"},
  {chord_base_id: 7, modification_ids: [12], base: 6, quality: "7add11"},
  {chord_base_id: 20, modification_ids: [], base: 11, quality: "m13"},
  {chord_base_id: 20, modification_ids: [], base: 4, quality: "m13"},
  {chord_base_id: 4, modification_ids: [11], base: 2, quality: "madd9"},
  {chord_base_id: 8, modification_ids: [3], base: 2, quality: "maj7b5"},
  {chord_base_id: 9, modification_ids: [14], base: 1, quality: "m7add13"},
  {chord_base_id: 4, modification_ids: [12], base: 12, quality: "madd11"}
])
