AllCops:
  Include:
    - 'app/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'bin/**'

Metrics/ModuleLength:
  Exclude:
    - 'app/constants/**/*.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20